# -*- coding: utf-8 -*-
"""Ace Team Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_HlDxt32neTn1S0UNdF4GSSchpY1i8P
"""

# ================================
# 1. Load Text File
# ================================
with open('meditations copy.text', "r", encoding="utf-8") as f:
    data = f.read()

print("Total text length:", len(data))

# ================================
# 2. Chunking (Sentence-based)
# ================================
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.tokenize import sent_tokenize

def split_into_sentence_chunks(text, max_chunk_length=500):
    sentences = sent_tokenize(text)

    chunks = []
    current_chunk = ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) > max_chunk_length:
            chunks.append(current_chunk)
            current_chunk = sentence
        else:
            current_chunk += " " + sentence

    if current_chunk:
        chunks.append(current_chunk)

    return chunks

sentence_chunks = split_into_sentence_chunks(data, 500)

# Clean chunks (remove noise + very small chunks)
sentence_chunks = [chunk.strip() for chunk in sentence_chunks if len(chunk.strip()) > 100]

# Remove headings like "MEDITATIONS"
sentence_chunks = [chunk for chunk in sentence_chunks if "MEDITATIONS" not in chunk[:50]]

print("Total cleaned chunks:", len(sentence_chunks))

# ================================
# 3. Embeddings (Offline)
# ================================
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(sentence_chunks)

print("Embedding shape:", embeddings.shape)

# ================================
# 4. FAISS Vector Database
# ================================
!pip install faiss-cpu
import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

print("FAISS index created with vectors:", index.ntotal)

# ================================
# 5. Search Function
# ================================
def search(query, k=3):
    query_vec = model.encode([query])

    distances, indices = index.search(np.array(query_vec), k)

    results = [sentence_chunks[i] for i in indices[0]]

    return results




import re

def clean_text(text):
    text = re.sub(r"MEDITATIONS OF MARCUS AURELIUS.*?(BOOK)?", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"Marcus Aurelius.*?Casaubon.*?(,|\.|$)", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"uploaded to .*?\d{4}", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"Page\s*\d+\s*of\s*\d+", " ", text, flags=re.IGNORECASE)

    text = re.sub(r"\b\d+\.\d+\b", " ", text)

    # remove ALL CAPS noise
    text = re.sub(r"\b[A-Z\s]{8,}\b", " ", text)

    # FIX commas and punctuation issues
    text = re.sub(r"\s*,\s*", ", ", text)   # normalize commas
    text = re.sub(r",\s*,+", ", ", text)    # remove repeated commas
    text = re.sub(r"\s+\.", ".", text)      # fix space before period

    # remove stray commas alone
    text = re.sub(r"\b,\b", " ", text)

    # normalize spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def answer_query(query):
    results = search(query, k=3)
    cleaned_chunks = [clean_text(r) for r in results]
    combined = " ".join(cleaned_chunks[:2])

    combined = combined[:400]  # limit length

    # end at last full stop
    last_period = combined.rfind(".")
    if last_period != -1:
        combined = combined[:last_period+1]

    return combined

# ================================
# 6. Query Example (Demo)
# ================================
query = "What does Marcus Aurelius say about controlling the mind?"

answer = answer_query(query)

print("\nAnswer:\n")
print(answer)